# Generated by Django 3.1.4 on 2020-12-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hash', models.CharField(max_length=32)),
                ('isEnc', models.BooleanField(default=False)),
                ('enc_key', models.CharField(max_length=32)),
                ('last_modified', models.DateField()),
            ],
        ),
    ]
